name: Test runing helix cli
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.12.0'
    - run: npm install
    - run: npx @adobe/helix-cli up --log-level silly
      env:
        CI: true